apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-clinica-hpa
spec:
  minReplicas: 1
  maxReplicas: 3  # Menos scaling em dev
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Threshold mais alto em dev