apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-clinica.fullname" . }}-secrets
  labels:
    {{- include "backend-clinica.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  META_WHATSAPP_TOKEN: {{ .Values.secrets.metaWhatsappToken | quote }}
  META_WHATSAPP_PHONE_ID: {{ .Values.secrets.metaWhatsappPhoneId | quote }}
  WHATSAPP_VERIFY_TOKEN: {{ .Values.secrets.whatsappVerifyToken | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  PINECONE_API_KEY: {{ .Values.secrets.pineconeApiKey | quote }}
  PINECONE_ENV: {{ .Values.secrets.pineconeEnv | quote }}
  PINECONE_INDEX: {{ .Values.secrets.pineconeIndex | quote }}