apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-clinica
spec:
  replicas: 3  # Mais réplicas em produção
  template:
    spec:
      containers:
      - name: backend-clinica
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"