apiVersion: v1
kind: Secret
metadata:
  name: backend-clinica-secrets
type: Opaque
stringData:
  # Database
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/clinica"
  
  # JWT
  JWT_SECRET: "your-super-secret-jwt-key-here"
  
  # WhatsApp API
  META_WHATSAPP_TOKEN: "your-whatsapp-token"
  META_WHATSAPP_PHONE_ID: "your-phone-id"
  WHATSAPP_VERIFY_TOKEN: "your-verify-token"
  
  # OpenAI
  OPENAI_API_KEY: "sk-your-openai-api-key"
  
  # Pinecone
  PINECONE_API_KEY: "your-pinecone-api-key"
  PINECONE_ENV: "us-east-1"
  PINECONE_INDEX: "clinica"